version: "3"

services:
  respira-confianza-db:
    container_name: respira-confianza-db
    build: ../respira-confianza-db
    restart: always
    env_file:
      - ../respira-confianza-db/.env
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata

  respira-confianza-pgadmin:
    container_name: respira-confianza-pgadmin
    build: ../respira-confianza-pgadmin
    env_file:
      - ../respira-confianza-pgadmin/.env
    depends_on:
      - respira-confianza-db
    expose:
      - 82

  respira-confianza-api:
    container_name: respira-confianza-api
    build: ../respira-confianza-api
    restart: always
    env_file:
      - ../respira-confianza-api/.env.docker
    volumes:
      - ./respira-confianza-api:/usr/src/app
    depends_on:
      - respira-confianza-db
    links:
      - respira-confianza-db
    expose:
      - 8080

  respira-confianza-mqtt:
    container_name: respira-confianza-mqtt
    build: ../respira-confianza-mqtt
    restart: always
    env_file:
      - ../respira-confianza-mqtt/.env.docker
    depends_on:
      - respira-confianza-api
    links:
      - respira-confianza-api

  respira-confianza-web:
    container_name: respira-confianza-web
    build: ../respira-confianza-web
    restart: always
    volumes:
      - ./respira-confianza-web:/usr/src/app
    env_file:
      - ../respira-confianza-web/.env.docker
    depends_on:
      - respira-confianza-api
    links:
      - respira-confianza-api
    expose:
      - 3000

  respira-confianza-nginx:
    container_name: respira-confianza-reverse-proxy
    build: ../respira-confianza-reverse-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - respira-confianza-web
      - respira-confianza-pgadmin
    links:
      - respira-confianza-api
      - respira-confianza-web
      - respira-confianza-pgadmin
    volumes:
      - ./data/nginx:/etc/nginx/conf.d

volumes:
  pgdata:
